version: '3.7'

services:
  web:
    build: ./services/web
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./services/web/:/usr/src/app/
      - ./data:/data
      - ./config:/config
    ports:
      - 5000:5000
    env_file:
      - ./dev.env

